

services:
  postgres:
    image: postgres:16
    container_name: banca-postgres
    environment:
      POSTGRES_DB: banca_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banca_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: "8081"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"

  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: "8082"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"

  movement-service:
    build: ./movement-service
    container_name: movement-service
    depends_on:
      postgres:
        condition: service_healthy
      account-service:
        condition: service_started
    environment:
      SERVER_PORT: "8083"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


      ACCOUNT_SERVICE_URL: http://account-service:8082
    ports:
      - "8083:8083"

  report-service:
    build: ./report-service
    container_name: report-service
    depends_on:
      customer-service:
        condition: service_started
      account-service:
        condition: service_started
      movement-service:
        condition: service_started
    environment:
      SERVER_PORT: "8084"

      # Feign URLs (hostname docker)
      services.customer.url: http://customer-service:8081
      services.account.url: http://account-service:8082
      services.movement.url: http://movement-service:8083
    ports:
      - "8084:8084"

volumes:
  pgdata: