spring.application.name=report-service
server.port=8084
services.customer.url=http://customer-service:8081
services.account.url=http://account-service:8082
services.movement.url=http://movement-service:8083
